update product requests
bloxapp/cluster-scanner pull request #3
Opened 2023-02-17 22:39 UTC by andrew-blox

2023-02-17 22:41 UTC, andrew-blox commented on examples/example-js.js
> +const { SSVScannerCommand } = require('../dist/tsc/src/commands/SSVScannerCommand');
I think this is wrong @meshin-blox

2023-02-17 22:48 UTC, andrew-blox commented
All things i updated can be found here
https://bloxxx.atlassian.net/browse/IO1-2628

2023-02-19 08:48 UTC, meshin-blox commented on examples/example-js.js
> +const { SSVScannerCommand } = require('../dist/tsc/src/commands/SSVScannerCommand');
That's correct, it should use package from node_modules

2023-02-19 09:02 UTC, meshin-blox requested changes
@andrew-blox please name your branches in future in this format:

```
ab/IO1-2628_cluster_scanner_product_review
```

```
<initials>/<story_number>_<underscored_lowercased_description>
```

2023-02-19 09:02 UTC, meshin-blox commented on src/commands/SSVScannerCommand.ts
> +    try { latestBlockNumber = await Web3Provider.web3(this.params.nodeUrl).eth.getBlockNumber(); }
Format this code block properly

2023-02-20 11:14 UTC, andrew-blox commented on examples/example-typescript.ts
> +}`);
updated

2023-02-20 11:16 UTC, andrew-blox commented on src/cli-shared.ts
> -  const messageText = `SSV Scanner v${pkg.version}`;
updated

2023-02-20 11:16 UTC, andrew-blox commented on src/cli-shared.ts
> +}`);
udpatec

2023-02-20 11:18 UTC, andrew-blox commented on src/commands/SSVScannerCommand.ts
> +    if (params_.contractAddress.slice(0, 2) !== '0x') throw Error('Invalid contract address.');
udpated

2023-02-20 11:19 UTC, andrew-blox commented on src/commands/SSVScannerCommand.ts
> +    if (params_.ownerAddress.slice(0, 2) !== '0x') throw Error('Invalid owner address.');
updated

2023-02-20 11:19 UTC, andrew-blox commented on src/commands/SSVScannerCommand.ts
> +    let latestBlockNumber
updated

2023-02-20 11:20 UTC, andrew-blox commented on src/commands/SSVScannerCommand.ts
> +    try { latestBlockNumber = await Web3Provider.web3(this.params.nodeUrl).eth.getBlockNumber(); }
updated

2023-02-20 11:54 UTC, meshin-blox approved these changes

2023-02-20 11:55 UTC, merged